name             'fluffy-psychic-spork'
maintainer       'fluffy-psychic-spork maintainer'
maintainer_email 'fluffy-psychic-spork@localhost'
license          'All rights reserved'
description      'Installs/Configures fluffy-psychic-spork'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'

depends 'compat_resource'
depends 'ohai'
depends 'apt'
depends 'windows'
depends 'seven_zip'
depends 'mingw'
depends 'yum'
depends 'yum-epel'
depends 'chef_handler'
depends 'dmg'
depends 'build-essential'
depends 'git'
depends 'rbenv'
